# Generated by Django 3.2.9 on 2024-09-14 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hava',
            fields=[
                ('weather_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=25)),
                ('temperature', models.FloatField()),
                ('expected_state', models.CharField(max_length=30)),
                ('humidity', models.FloatField()),
                ('wind', models.FloatField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='searchForCity',
            fields=[
                ('city_id', models.AutoField(primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
