# Generated by Django 4.2.16 on 2024-09-26 14:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="jobs",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("city_name", models.CharField(max_length=25)),
            ],
        ),
    ]
