# Generated by Django 3.2.9 on 2024-08-18 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hava',
            name='humidity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hava',
            name='rainfall',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hava',
            name='weather_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='hava',
            name='wind',
            field=models.FloatField(),
        ),
    ]
