# Generated by Django 3.2.9 on 2024-08-18 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20240818_1555'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hava',
            name='rainfall',
        ),
    ]
