# Generated by Django 3.2.9 on 2024-08-18 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_remove_hava_rainfall'),
    ]

    operations = [
        migrations.CreateModel(
            name='searchForCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=30)),
            ],
        ),
    ]
