# Generated by Django 3.2.9 on 2024-08-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_searchforcity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchforcity',
            name='id',
        ),
        migrations.AddField(
            model_name='searchforcity',
            name='city_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
